CREATE TABLE dict_table (
    ID INT PRIMARY KEY,
    DICT VARCHAR(255),
    CODE VARCHAR(255),
    KEY VARCHAR(255),
    TEXT_E VARCHAR(255),
    ENTITY_TYPE VARCHAR(255),
    IS_NUMERIC BOOLEAN,
    IS_EDITABLE BOOLEAN,
    INST_ID INT,
    MODULE_CODE VARCHAR(255)
);
