use botransactions;
CREATE TABLE operations (
     id INT AUTO_INCREMENT PRIMARY KEY,
     acq_inst_bin VARCHAR(25),
     acquirer_account_number VARCHAR(50),
     acquirer_inst_id VARCHAR(10),
     acquirer_merchant_id VARCHAR(15),
     acquirer_network_id VARCHAR(16),
     acquirer_terminal_id VARCHAR(16),
     auth_data_account_cnvt_rate VARCHAR(12),
     auth_data_acq_device_proc_result VARCHAR(10),
     auth_data_acq_resp_code VARCHAR(8),
     auth_data_addl_data VARCHAR(1024),
     auth_data_amounts VARCHAR(2048),
     auth_data_atc VARCHAR(25),
     auth_data_auth_tag VARCHAR(25),
     auth_data_auth_transaction_id VARCHAR(25),
     auth_data_bin_amount VARCHAR(25),
     auth_data_bin_cnvt_rate VARCHAR(25),
     auth_data_bin_currency VARCHAR(3),
     auth_data_card_capture_cap VARCHAR(25),
     auth_data_card_data_input_cap VARCHAR(25),
     auth_data_card_data_input_mode VARCHAR(25),
     auth_data_card_data_output_cap VARCHAR(25),
     auth_data_card_presence VARCHAR(25),
     auth_data_cat_level VARCHAR(25),
     auth_data_certificate_method VARCHAR(25),
     auth_data_crdh_auth_cap VARCHAR(25),
     auth_data_crdh_auth_entity VARCHAR(25),
     auth_data_crdh_auth_method VARCHAR(25),
     auth_data_crdh_presence VARCHAR(25),
     auth_data_cvr VARCHAR(25),
     auth_data_cvv2_presence VARCHAR(25),
     auth_data_cvv2_result VARCHAR(25),
     auth_data_device_date VARCHAR(20),
     auth_data_emv_data VARCHAR(2048),
     auth_data_external_auth_id VARCHAR(20),
     auth_data_external_orig_id VARCHAR(20),
     auth_data_is_advice VARCHAR(1),
     auth_data_is_completed VARCHAR(8),
     auth_data_is_early_emv VARCHAR(1),
     auth_data_is_repeat VARCHAR(1),
     auth_data_network_amount VARCHAR(25),
     auth_data_network_cnvt_date VARCHAR(20),
     auth_data_network_currency VARCHAR(3),
     auth_data_pin_capture_cap VARCHAR(25),
     auth_data_pin_presence VARCHAR(25),
     auth_data_pos_cond_code VARCHAR(25),
     auth_data_pos_entry_mode VARCHAR(25),
     auth_data_proc_mode VARCHAR(25),
     auth_data_proc_type VARCHAR(25),
     auth_data_resp_code VARCHAR(25),
     auth_data_service_code VARCHAR(25),
     auth_data_terminal_operating_env VARCHAR(25),
     auth_data_terminal_output_cap VARCHAR(25),
     auth_data_trace_number VARCHAR(25),
     auth_data_tvr VARCHAR(25),
     auth_data_ucaf_indicator VARCHAR(10),
     host_date DATETIME,
     is_reversal VARCHAR(1),
     issuer_auth_code VARCHAR(10),
     issuer_card_country VARCHAR(25),
     issuer_card_expir_date VARCHAR(25),
     issuer_card_id VARCHAR(25),
     issuer_card_instance_id VARCHAR(25),
     issuer_card_network_id VARCHAR(25),
     issuer_card_number VARCHAR(19),
     issuer_card_seq_number VARCHAR(10),
     issuer_inst_id VARCHAR(10),
     issuer_network_id VARCHAR(25),
     mcc VARCHAR(4),
     merchant_city VARCHAR(50),
     merchant_country VARCHAR(50),
     merchant_name VARCHAR(50),
     merchant_number VARCHAR(15),
     merchant_postcode VARCHAR(10),
     merchant_region VARCHAR(50),
     merchant_street VARCHAR(50),
     msg_type VARCHAR(8),
     network_refnum VARCHAR(50),
     oper_amount_amount_value VARCHAR(25),
     oper_amount_currency VARCHAR(3),
     oper_date DATETIME,
     oper_id VARCHAR(20),
     oper_surcharge_amount_amount_value VARCHAR(25),
     oper_surcharge_amount_currency VARCHAR(3),
     oper_type VARCHAR(8),
     original_id VARCHAR(50),
     originator_refnum VARCHAR(25),
     payment_order_id VARCHAR(25),
     status VARCHAR(8),
     sttl_amount_amount_value VARCHAR(25),
     sttl_amount_currency VARCHAR(3),
     sttl_type VARCHAR(8),
     terminal_number VARCHAR(15),
     terminal_type VARCHAR(8),
     transaction_amount_purpose VARCHAR(25),
     transaction_conversion_rate VARCHAR(64),
     transaction_credit_entry VARCHAR(25),
     transaction_debit_entry VARCHAR(25),
     transaction_fee VARCHAR(25),
     transaction_posting_date VARCHAR(20),
     transaction_transaction_id VARCHAR(50),
     transaction_transaction_type VARCHAR(50)
 );
 
 -- correct units to decimal rub.cop or doll.cent
ALTER TABLE operations ADD COLUMN oper_amount_amount_value_corrected DECIMAL(15, 2);
UPDATE operations SET oper_amount_amount_value_corrected = CAST(oper_amount_amount_value AS DECIMAL(15, 2)) / 100;
ALTER TABLE operations DROP COLUMN oper_amount_amount_value;
ALTER TABLE operations CHANGE COLUMN oper_amount_amount_value_corrected oper_amount_amount_value DECIMAL(15, 2);


USE botransactions;

ALTER TABLE operations
    MODIFY COLUMN id INT AUTO_INCREMENT COMMENT 'Unique identifier for the operation',
    MODIFY COLUMN acq_inst_bin VARCHAR(25) COMMENT 'Acquirer institution BIN',
    MODIFY COLUMN acquirer_account_number VARCHAR(50) COMMENT 'Acquirer account number',
    MODIFY COLUMN acquirer_inst_id VARCHAR(10) COMMENT 'Acquirer institution ID',
    MODIFY COLUMN acquirer_merchant_id VARCHAR(15) COMMENT 'Acquirer merchant ID',
    MODIFY COLUMN acquirer_network_id VARCHAR(16) COMMENT 'Acquirer network ID',
    MODIFY COLUMN acquirer_terminal_id VARCHAR(16) COMMENT 'Acquirer terminal ID',
    MODIFY COLUMN auth_data_account_cnvt_rate VARCHAR(12) COMMENT 'Account conversion rate for authorization data',
    MODIFY COLUMN auth_data_acq_device_proc_result VARCHAR(10) COMMENT 'Acquirer device processing result for authorization data',
    MODIFY COLUMN auth_data_acq_resp_code VARCHAR(8) COMMENT 'Acquirer response code for authorization data',
    MODIFY COLUMN auth_data_addl_data VARCHAR(1024) COMMENT 'Additional data for authorization',
    MODIFY COLUMN auth_data_amounts VARCHAR(2048) COMMENT 'Amounts related to authorization data',
    MODIFY COLUMN auth_data_atc VARCHAR(25) COMMENT 'Application Transaction Counter for authorization data',
    MODIFY COLUMN auth_data_auth_tag VARCHAR(25) COMMENT 'Authorization tag for authorization data',
    MODIFY COLUMN auth_data_auth_transaction_id VARCHAR(25) COMMENT 'Authorization transaction ID',
    MODIFY COLUMN auth_data_bin_amount VARCHAR(25) COMMENT 'BIN amount for authorization data',
    MODIFY COLUMN auth_data_bin_cnvt_rate VARCHAR(25) COMMENT 'BIN conversion rate for authorization data',
    MODIFY COLUMN auth_data_bin_currency VARCHAR(3) COMMENT 'BIN currency for authorization data',
    MODIFY COLUMN auth_data_card_capture_cap VARCHAR(25) COMMENT 'Card capture capability for authorization data',
    MODIFY COLUMN auth_data_card_data_input_cap VARCHAR(25) COMMENT 'Card data input capability for authorization data',
    MODIFY COLUMN auth_data_card_data_input_mode VARCHAR(25) COMMENT 'Card data input mode for authorization data',
    MODIFY COLUMN auth_data_card_data_output_cap VARCHAR(25) COMMENT 'Card data output capability for authorization data',
    MODIFY COLUMN auth_data_card_presence VARCHAR(25) COMMENT 'Card presence for authorization data',
    MODIFY COLUMN auth_data_cat_level VARCHAR(25) COMMENT 'Category level for authorization data',
    MODIFY COLUMN auth_data_certificate_method VARCHAR(25) COMMENT 'Certificate method for authorization data',
    MODIFY COLUMN auth_data_crdh_auth_cap VARCHAR(25) COMMENT 'Cardholder authentication capability for authorization data',
    MODIFY COLUMN auth_data_crdh_auth_entity VARCHAR(25) COMMENT 'Cardholder authentication entity for authorization data',
    MODIFY COLUMN auth_data_crdh_auth_method VARCHAR(25) COMMENT 'Cardholder authentication method for authorization data',
    MODIFY COLUMN auth_data_crdh_presence VARCHAR(25) COMMENT 'Cardholder presence for authorization data',
    MODIFY COLUMN auth_data_cvr VARCHAR(25) COMMENT 'Card Verification Result for authorization data',
    MODIFY COLUMN auth_data_cvv2_presence VARCHAR(25) COMMENT 'CVV2 presence for authorization data',
    MODIFY COLUMN auth_data_cvv2_result VARCHAR(25) COMMENT 'CVV2 result for authorization data',
    MODIFY COLUMN auth_data_device_date VARCHAR(20) COMMENT 'Device date for authorization data',
    MODIFY COLUMN auth_data_emv_data VARCHAR(2048) COMMENT 'EMV data for authorization',
    MODIFY COLUMN auth_data_external_auth_id VARCHAR(20) COMMENT 'External authorization ID',
    MODIFY COLUMN auth_data_external_orig_id VARCHAR(20) COMMENT 'External origin ID for authorization data',
    MODIFY COLUMN auth_data_is_advice VARCHAR(1) COMMENT 'Indicates if the authorization data is advice',
    MODIFY COLUMN auth_data_is_completed VARCHAR(8) COMMENT 'Indicates if the authorization data is completed',
    MODIFY COLUMN auth_data_is_early_emv VARCHAR(1) COMMENT 'Indicates if the authorization data is early EMV',
    MODIFY COLUMN auth_data_is_repeat VARCHAR(1) COMMENT 'Indicates if the authorization data is a repeat',
    MODIFY COLUMN auth_data_network_amount VARCHAR(25) COMMENT 'Network amount for authorization data',
    MODIFY COLUMN auth_data_network_cnvt_date VARCHAR(20) COMMENT 'Network conversion date for authorization data',
    MODIFY COLUMN auth_data_network_currency VARCHAR(3) COMMENT 'Network currency for authorization data',
    MODIFY COLUMN auth_data_pin_capture_cap VARCHAR(25) COMMENT 'PIN capture capability for authorization data',
    MODIFY COLUMN auth_data_pin_presence VARCHAR(25) COMMENT 'PIN presence for authorization data',
    MODIFY COLUMN auth_data_pos_cond_code VARCHAR(25) COMMENT 'POS condition code for authorization data',
    MODIFY COLUMN auth_data_pos_entry_mode VARCHAR(25) COMMENT 'POS entry mode for authorization data',
    MODIFY COLUMN auth_data_proc_mode VARCHAR(25) COMMENT 'Processing mode for authorization data',
    MODIFY COLUMN auth_data_proc_type VARCHAR(25) COMMENT 'Processing type for authorization data',
    MODIFY COLUMN auth_data_resp_code VARCHAR(25) COMMENT 'Response code for authorization data',
    MODIFY COLUMN auth_data_service_code VARCHAR(25) COMMENT 'Service code for authorization data',
    MODIFY COLUMN auth_data_terminal_operating_env VARCHAR(25) COMMENT 'Terminal operating environment for authorization data',
    MODIFY COLUMN auth_data_terminal_output_cap VARCHAR(25) COMMENT 'Terminal output capability for authorization data',
    MODIFY COLUMN auth_data_trace_number VARCHAR(25) COMMENT 'Trace number for authorization data',
    MODIFY COLUMN auth_data_tvr VARCHAR(25) COMMENT 'Terminal Verification Results for authorization data',
    MODIFY COLUMN auth_data_ucaf_indicator VARCHAR(10) COMMENT 'UCAF indicator for authorization data',
    MODIFY COLUMN host_date DATETIME COMMENT 'Host date and time of the operation',
    MODIFY COLUMN is_reversal VARCHAR(1) COMMENT 'Indicates if the operation is a reversal',
    MODIFY COLUMN issuer_auth_code VARCHAR(10) COMMENT 'Issuer authorization code',
    MODIFY COLUMN issuer_card_country VARCHAR(25) COMMENT 'Issuer card country',
    MODIFY COLUMN issuer_card_expir_date VARCHAR(25) COMMENT 'Issuer card expiration date',
    MODIFY COLUMN issuer_card_id VARCHAR(25) COMMENT 'Issuer card ID',
    MODIFY COLUMN issuer_card_instance_id VARCHAR(25) COMMENT 'Issuer card instance ID',
    MODIFY COLUMN issuer_card_network_id VARCHAR(25) COMMENT 'Issuer card network ID',
    MODIFY COLUMN issuer_card_number VARCHAR(19) COMMENT 'Issuer card number',
    MODIFY COLUMN issuer_card_seq_number VARCHAR(10) COMMENT 'Issuer card sequence number',
    MODIFY COLUMN issuer_inst_id VARCHAR(10) COMMENT 'Issuer institution ID',
    MODIFY COLUMN issuer_network_id VARCHAR(25) COMMENT 'Issuer network ID',
    MODIFY COLUMN mcc VARCHAR(4) COMMENT 'Merchant Category Code',
    MODIFY COLUMN merchant_city VARCHAR(50) COMMENT 'Merchant city',
    MODIFY COLUMN merchant_country VARCHAR(50) COMMENT 'Merchant country',
    MODIFY COLUMN merchant_name VARCHAR(50) COMMENT 'Merchant name',
    MODIFY COLUMN merchant_number VARCHAR(15) COMMENT 'Merchant number',
    MODIFY COLUMN merchant_postcode VARCHAR(10) COMMENT 'Merchant postcode',
    MODIFY COLUMN merchant_region VARCHAR(50) COMMENT 'Merchant region',
    MODIFY COLUMN merchant_street VARCHAR(50) COMMENT 'Merchant street',
    MODIFY COLUMN msg_type VARCHAR(8) COMMENT 'Message type',
    MODIFY COLUMN network_refnum VARCHAR(50) COMMENT 'Network reference number',
    MODIFY COLUMN oper_amount_amount_value VARCHAR(25) COMMENT 'Operation amount value',
    MODIFY COLUMN oper_amount_currency VARCHAR(3) COMMENT 'Operation amount currency',
    MODIFY COLUMN oper_date DATETIME COMMENT 'Operation date and time',
    MODIFY COLUMN oper_id VARCHAR(20) COMMENT 'Operation ID',
    MODIFY COLUMN oper_surcharge_amount_amount_value VARCHAR(25) COMMENT 'Operation surcharge amount value',
    MODIFY COLUMN oper_surcharge_amount_currency VARCHAR(3) COMMENT 'Operation surcharge amount currency',
    MODIFY COLUMN oper_type VARCHAR(8) COMMENT 'Operation type, lookup in OPTP dictionary',
    MODIFY COLUMN original_id VARCHAR(50) COMMENT 'Original operation ID',
    MODIFY COLUMN originator_refnum VARCHAR(25) COMMENT 'Originator reference number',
    MODIFY COLUMN payment_order_id VARCHAR(25) COMMENT 'Payment order ID',
    MODIFY COLUMN status VARCHAR(8) COMMENT 'Status of the operation',
    MODIFY COLUMN sttl_amount_amount_value VARCHAR(25) COMMENT 'Settlement amount value',
    MODIFY COLUMN sttl_amount_currency VARCHAR(3) COMMENT 'Settlement amount currency',
    MODIFY COLUMN sttl_type VARCHAR(8) COMMENT 'Settlement type',
    MODIFY COLUMN terminal_number VARCHAR(15) COMMENT 'Terminal number',
    MODIFY COLUMN terminal_type VARCHAR(8) COMMENT 'Terminal type',
    MODIFY COLUMN transaction_amount_purpose VARCHAR(25) COMMENT 'Purpose of the transaction amount',
    MODIFY COLUMN transaction_conversion_rate VARCHAR(64) COMMENT 'Transaction conversion rate',
    MODIFY COLUMN transaction_credit_entry VARCHAR(25) COMMENT 'Transaction credit entry',
    MODIFY COLUMN transaction_debit_entry VARCHAR(25) COMMENT 'Transaction debit entry',
    MODIFY COLUMN transaction_fee VARCHAR(25) COMMENT 'Transaction fee',
    MODIFY COLUMN transaction_posting_date VARCHAR(20) COMMENT 'Transaction posting date',
    MODIFY COLUMN transaction_transaction_id VARCHAR(50) COMMENT 'Transaction ID',
    MODIFY COLUMN transaction_transaction_type VARCHAR(50) COMMENT 'Transaction type';

ALTER TABLE operations COMMENT = 'Table storing details of customers\' operations on bank cards';




