USE botransactions;
CREATE TABLE customers (
    customer VARCHAR(255),
    customer_address VARCHAR(255),
    customer_address_address_name VARCHAR(255),
    customer_address_address_name_city VARCHAR(6),
    customer_address_address_name_comment VARCHAR(255),
    customer_address_address_name_region VARCHAR(9),
    customer_address_address_name_street VARCHAR(36),
    customer_address_address_type VARCHAR(8),
    customer_address_apartment VARCHAR(4),
    customer_address_country VARCHAR(3),
    customer_address_house VARCHAR(5),
    customer_company VARCHAR(255),
    customer_company_company_name VARCHAR(255),
    customer_company_company_name_company_full_name VARCHAR(28),
    customer_company_company_name_company_short_name VARCHAR(28),
    customer_company_embossed_name VARCHAR(15),
    customer_company_identity_card VARCHAR(255),
    customer_company_identity_card_id_issue_date VARCHAR(10),
    customer_company_identity_card_id_number VARCHAR(6),
    customer_company_identity_card_id_series VARCHAR(4),
    customer_company_identity_card_id_type VARCHAR(8),
    customer_company_incorp_form VARCHAR(8),
    customer_contact VARCHAR(255),
    customer_contact_contact_data VARCHAR(255),
    customer_contact_contact_data_commun_address VARCHAR(16),
    customer_contact_contact_data_commun_method VARCHAR(8),
    customer_contact_contact_data_start_date VARCHAR(19),
    customer_contact_contact_type VARCHAR(8),
    customer_contact_job_title VARCHAR(8),
    customer_contact_person VARCHAR(255),
    customer_contact_person_identity_card VARCHAR(255),
    customer_contact_person_identity_card_id_number VARCHAR(6),
    customer_contact_person_identity_card_id_series VARCHAR(4),
    customer_contact_person_identity_card_id_type VARCHAR(8),
    customer_contact_person_person_name VARCHAR(255),
    customer_contact_person_person_name_first_name VARCHAR(10),
    customer_contact_person_person_name_second_name VARCHAR(16),
    customer_contact_person_person_name_surname VARCHAR(11),
    customer_contact_preferred_lang VARCHAR(7),
    customer_contract VARCHAR(255),
    customer_contract_agent_id VARCHAR(8),
    customer_contract_agent_number VARCHAR(6),
    customer_contract_contract_number VARCHAR(47),
    customer_contract_contract_type VARCHAR(8),
    customer_contract_end_date VARCHAR(10),
    customer_contract_product_id VARCHAR(8),
    customer_contract_product_number VARCHAR(8),
    customer_contract_start_date VARCHAR(10),
    customer_customer_category VARCHAR(8),
    customer_customer_ext_id VARCHAR(8),
    customer_customer_ext_type VARCHAR(8),
    customer_customer_number VARCHAR(23),
    customer_customer_relation VARCHAR(8),
    customer_inst_id VARCHAR(4),
    customer_money_laundry_reason VARCHAR(8),
    customer_money_laundry_risk VARCHAR(8),
    customer_nationality VARCHAR(3),
    customer_note VARCHAR(255),
    customer_note_note_content VARCHAR(255),
    customer_note_note_content_note_header VARCHAR(19),
    customer_note_note_content_note_text VARCHAR(19),
    customer_note_note_type VARCHAR(8),
    customer_person VARCHAR(255),
    customer_person_birthday VARCHAR(10),
    customer_person_gender VARCHAR(8),
    customer_person_identity_card VARCHAR(255),
    customer_person_identity_card_id_issuer VARCHAR(64),
    customer_person_identity_card_id_number VARCHAR(12),
    customer_person_identity_card_id_series VARCHAR(12),
    customer_person_identity_card_id_type VARCHAR(8),
    customer_person_person_name VARCHAR(255),
    customer_person_person_name_first_name VARCHAR(11),
    customer_person_person_name_second_name VARCHAR(16),
    customer_person_person_name_surname VARCHAR(22),
    customer_person_person_title VARCHAR(8),
    customer_person_place_of_birth VARCHAR(44),
    customer_person_suffix VARCHAR(8),
    customer_resident VARCHAR(1),
    customer_status VARCHAR(8),
    file_id VARCHAR(16),
    file_type VARCHAR(8),
    inst_id VARCHAR(4)
);


ALTER TABLE customers
    MODIFY COLUMN customer VARCHAR(255) COMMENT 'Unique customer identifier',
    MODIFY COLUMN customer_address VARCHAR(255) COMMENT 'Customer address',
    MODIFY COLUMN customer_address_address_name VARCHAR(255) COMMENT 'Name of the address',
    MODIFY COLUMN customer_address_address_name_city VARCHAR(6) COMMENT 'City of the address',
    MODIFY COLUMN customer_address_address_name_comment VARCHAR(255) COMMENT 'Comment related to the address',
    MODIFY COLUMN customer_address_address_name_region VARCHAR(9) COMMENT 'Region of the address',
    MODIFY COLUMN customer_address_address_name_street VARCHAR(36) COMMENT 'Street of the address',
    MODIFY COLUMN customer_address_address_type VARCHAR(8) COMMENT 'Type of the address (e.g., residential, commercial)',
    MODIFY COLUMN customer_address_apartment VARCHAR(4) COMMENT 'Apartment number',
    MODIFY COLUMN customer_address_country VARCHAR(3) COMMENT 'Country of the address',
    MODIFY COLUMN customer_address_house VARCHAR(5) COMMENT 'House number',
    MODIFY COLUMN customer_company VARCHAR(255) COMMENT 'Company identifier or name',
    MODIFY COLUMN customer_company_company_name VARCHAR(255) COMMENT 'Company name',
    MODIFY COLUMN customer_company_company_name_company_full_name VARCHAR(28) COMMENT 'Full name of the company',
    MODIFY COLUMN customer_company_company_name_company_short_name VARCHAR(28) COMMENT 'Short name of the company',
    MODIFY COLUMN customer_company_embossed_name VARCHAR(15) COMMENT 'Embossed name on the company card',
    MODIFY COLUMN customer_company_identity_card VARCHAR(255) COMMENT 'Company identity card details',
    MODIFY COLUMN customer_company_identity_card_id_issue_date VARCHAR(10) COMMENT 'Issue date of the company identity card',
    MODIFY COLUMN customer_company_identity_card_id_number VARCHAR(6) COMMENT 'Identity card number of the company',
    MODIFY COLUMN customer_company_identity_card_id_series VARCHAR(4) COMMENT 'Series of the company identity card',
    MODIFY COLUMN customer_company_identity_card_id_type VARCHAR(8) COMMENT 'Type of the company identity card',
    MODIFY COLUMN customer_company_incorp_form VARCHAR(8) COMMENT 'Incorporation form of the company',
    MODIFY COLUMN customer_contact VARCHAR(255) COMMENT 'Contact identifier or name',
    MODIFY COLUMN customer_contact_contact_data VARCHAR(255) COMMENT 'Contact data details',
    MODIFY COLUMN customer_contact_contact_data_commun_address VARCHAR(16) COMMENT 'Communication address of the contact',
    MODIFY COLUMN customer_contact_contact_data_commun_method VARCHAR(8) COMMENT 'Communication method of the contact',
    MODIFY COLUMN customer_contact_contact_data_start_date VARCHAR(19) COMMENT 'Start date of the contact data',
    MODIFY COLUMN customer_contact_contact_type VARCHAR(8) COMMENT 'Type of the contact',
    MODIFY COLUMN customer_contact_job_title VARCHAR(8) COMMENT 'Job title of the contact person',
    MODIFY COLUMN customer_contact_person VARCHAR(255) COMMENT 'Contact person identifier or name',
    MODIFY COLUMN customer_contact_person_identity_card VARCHAR(255) COMMENT 'Identity card details of the contact person',
    MODIFY COLUMN customer_contact_person_identity_card_id_number VARCHAR(6) COMMENT 'Identity card number of the contact person',
    MODIFY COLUMN customer_contact_person_identity_card_id_series VARCHAR(4) COMMENT 'Series of the contact person identity card',
    MODIFY COLUMN customer_contact_person_identity_card_id_type VARCHAR(8) COMMENT 'Type of the contact person identity card',
    MODIFY COLUMN customer_contact_person_person_name VARCHAR(255) COMMENT 'Name of the contact person',
    MODIFY COLUMN customer_contact_person_person_name_first_name VARCHAR(10) COMMENT 'First name of the contact person',
    MODIFY COLUMN customer_contact_person_person_name_second_name VARCHAR(16) COMMENT 'Second name of the contact person',
    MODIFY COLUMN customer_contact_person_person_name_surname VARCHAR(11) COMMENT 'Surname of the contact person',
    MODIFY COLUMN customer_contact_preferred_lang VARCHAR(7) COMMENT 'Preferred language of the contact person',
    MODIFY COLUMN customer_contract VARCHAR(255) COMMENT 'Contract identifier or name',
    MODIFY COLUMN customer_contract_agent_id VARCHAR(8) COMMENT 'Agent ID related to the contract',
    MODIFY COLUMN customer_contract_agent_number VARCHAR(6) COMMENT 'Agent number related to the contract',
    MODIFY COLUMN customer_contract_contract_number VARCHAR(47) COMMENT 'Contract number',
    MODIFY COLUMN customer_contract_contract_type VARCHAR(8) COMMENT 'Type of the contract',
    MODIFY COLUMN customer_contract_end_date VARCHAR(10) COMMENT 'End date of the contract',
    MODIFY COLUMN customer_contract_product_id VARCHAR(8) COMMENT 'Product ID related to the contract',
    MODIFY COLUMN customer_contract_product_number VARCHAR(8) COMMENT 'Product number related to the contract',
    MODIFY COLUMN customer_contract_start_date VARCHAR(10) COMMENT 'Start date of the contract',
    MODIFY COLUMN customer_customer_category VARCHAR(8) COMMENT 'Category of the customer',
    MODIFY COLUMN customer_customer_ext_id VARCHAR(8) COMMENT 'External ID of the customer',
    MODIFY COLUMN customer_customer_ext_type VARCHAR(8) COMMENT 'External type of the customer',
    MODIFY COLUMN customer_customer_number VARCHAR(23) COMMENT 'Customer number',
    MODIFY COLUMN customer_customer_relation VARCHAR(8) COMMENT 'Relation of the customer',
    MODIFY COLUMN customer_inst_id VARCHAR(4) COMMENT 'Institution ID related to the customer',
    MODIFY COLUMN customer_money_laundry_reason VARCHAR(8) COMMENT 'Reason for money laundry check',
    MODIFY COLUMN customer_money_laundry_risk VARCHAR(8) COMMENT 'Risk level for money laundry',
    MODIFY COLUMN customer_nationality VARCHAR(3) COMMENT 'Nationality of the customer',
    MODIFY COLUMN customer_note VARCHAR(255) COMMENT 'Note related to the customer',
    MODIFY COLUMN customer_note_note_content VARCHAR(255) COMMENT 'Content of the note',
    MODIFY COLUMN customer_note_note_content_note_header VARCHAR(19) COMMENT 'Header of the note content',
    MODIFY COLUMN customer_note_note_content_note_text VARCHAR(19) COMMENT 'Text of the note content',
    MODIFY COLUMN customer_note_note_type VARCHAR(8) COMMENT 'Type of the note',
    MODIFY COLUMN customer_person VARCHAR(255) COMMENT 'Person identifier or name',
    MODIFY COLUMN customer_person_birthday VARCHAR(10) COMMENT 'Birthday of the person',
    MODIFY COLUMN customer_person_gender VARCHAR(8) COMMENT 'Gender of the person',
    MODIFY COLUMN customer_person_identity_card VARCHAR(255) COMMENT 'Identity card details of the person',
    MODIFY COLUMN customer_person_identity_card_id_issuer VARCHAR(64) COMMENT 'Issuer of the identity card',
    MODIFY COLUMN customer_person_identity_card_id_number VARCHAR(12) COMMENT 'Identity card number of the person',
    MODIFY COLUMN customer_person_identity_card_id_series VARCHAR(12) COMMENT 'Series of the identity card',
    MODIFY COLUMN customer_person_identity_card_id_type VARCHAR(8) COMMENT 'Type of the identity card',
    MODIFY COLUMN customer_person_person_name VARCHAR(255) COMMENT 'Name of the person',
    MODIFY COLUMN customer_person_person_name_first_name VARCHAR(11) COMMENT 'First name of the person',
    MODIFY COLUMN customer_person_person_name_second_name VARCHAR(16) COMMENT 'Second name of the person',
    MODIFY COLUMN customer_person_person_name_surname VARCHAR(22) COMMENT 'Surname of the person',
    MODIFY COLUMN customer_person_person_title VARCHAR(8) COMMENT 'Title of the person (Mr. Mrs.)',
    MODIFY COLUMN customer_person_place_of_birth VARCHAR(44) COMMENT 'Place of birth of the person',
    MODIFY COLUMN customer_person_suffix VARCHAR(8) COMMENT 'Suffix of the person (Jr.)',
    MODIFY COLUMN customer_resident VARCHAR(1) COMMENT 'Resident status of the customer',
    MODIFY COLUMN customer_status VARCHAR(8) COMMENT 'Status of the customer',
    MODIFY COLUMN file_id VARCHAR(16) COMMENT 'File ID related to the customer',
    MODIFY COLUMN file_type VARCHAR(8) COMMENT 'Type of the file',
    MODIFY COLUMN inst_id VARCHAR(4) COMMENT 'Institution ID in which customer registered';
ALTER TABLE customers
CHANGE COLUMN customer customer_id VARCHAR(255) COMMENT 'Unique customer identifier';

ALTER TABLE customers COMMENT = 'Table storing detailed information about customers, including personal, address, company, contact, contract, and other relevant details';

