-- Retrieve column comments
SELECT TABLE_NAME, COLUMN_NAME, COLUMN_COMMENT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'botransactions' AND TABLE_NAME = 'customers';

-- Retrieve table comment
SELECT TABLE_NAME, TABLE_COMMENT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'botransactions' AND TABLE_NAME = 'customers';
